# Generated by Django 5.2.4 on 2025-07-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="note",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
