# Generated by Django 5.2.4 on 2025-07-17 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0002_alter_stockmovement_date_alter_stockmovement_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
