# Generated by Django 5.2.4 on 2025-07-19 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0003_alter_stockmovement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api_v1.supplier"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api_v1.product"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api_v1.category"
            ),
        ),
    ]
