# Generated by Django 5.2.4 on 2025-07-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0004_alter_product_supplier_alter_stockmovement_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="supplier",
                to="api_v1.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product",
                to="api_v1.product",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="category",
                to="api_v1.category",
            ),
        ),
    ]
